import puppeteer from 'puppeteer';
import { format } from 'date-fns';

export async function generateContractPDF(contract: any) {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #000; padding-bottom: 20px; }
            .title { font-size: 24px; font-weight: bold; text-transform: uppercase; }
            .meta { margin-bottom: 30px; }
            .section { margin-bottom: 20px; }
            .section-title { font-weight: bold; text-transform: uppercase; font-size: 14px; border-bottom: 1px solid #ccc; margin-bottom: 10px; }
            .footer { margin-top: 50px; font-size: 12px; text-align: center; color: #666; }
            .signature-box { margin-top: 60px; display: flex; justify-content: space-between; }
            .sign-line { border-top: 1px solid #000; width: 200px; padding-top: 10px; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="title">Independent Contractor Agreement</div>
            <p>GWD Global Pvt Ltd</p>
        </div>

        <div class="meta">
            <p><strong>Date:</strong> ${format(new Date(), 'MMMM dd, yyyy')}</p>
            <p><strong>Contract No:</strong> ${contract.contractNumber}</p>
            <p><strong>Project:</strong> ${contract.project?.title}</p>
        </div>

        <div class="section">
            <div class="section-title">Parties</div>
            <p>This Agreement is made between <strong>GWD Global Pvt Ltd</strong> ("Company") and <strong>${contract.freelancer?.name}</strong> ("Contractor").</p>
        </div>

        <div class="section">
            <div class="section-title">1. Services & Scope</div>
            <p>${contract.scopeOfWork}</p>
            <ul>
                ${contract.deliverables?.map((d: string) => `<li>${d}</li>`).join('') || ''}
            </ul>
        </div>

        <div class="section">
            <div class="section-title">2. Term</div>
            <p>Start Date: ${format(new Date(contract.startDate), 'MMM dd, yyyy')}</p>
            <p>End Date: ${contract.endDate ? format(new Date(contract.endDate), 'MMM dd, yyyy') : 'Until Completion'}</p>
        </div>

        <div class="section">
            <div class="section-title">3. Compensation</div>
            <p>The Company shall pay the Contractor <strong>${new Intl.NumberFormat('en-US', { style: 'currency', currency: contract.currency || 'USD' }).format(contract.amount)}</strong>.</p>
            <p>Payment Terms: ${contract.paymentSchedule || 'Upon completion'}</p>
        </div>

        <div class="section">
            <div class="section-title">4. Confidentiality & IP</div>
            <p><strong>White-Label Clause:</strong> The Contractor agrees that they shall not disclose their engagement with the Company to any third party, including the Company's clients. All work is performed under the Company's brand.</p>
            <p><strong>Intellectual Property:</strong> All work product created under this Agreement shall be considered "Work for Hire" and the sole property of the Company.</p>
        </div>

        <div class="signature-box">
            <div>
                <div class="sign-line">GWD Global Representative</div>
                <p>Date: _________________</p>
            </div>
            <div>
                <div class="sign-line">${contract.freelancer?.name}</div>
                <p>Date: _________________</p>
            </div>
        </div>

        <div class="footer">
            Generated by GWD OS | Confidential
        </div>
    </body>
    </html>
    `;

    await page.setContent(htmlContent);
    const pdf = await page.pdf({ format: 'A4' });
    await browser.close();
    return pdf;
}
